title: "GeomechMotion – PLAXIS"
description: "Animaciones y videos sobre PLAXIS (procedimientos, K0, modelos constitutivos)."

url: "https://geomechmotion.github.io"
baseurl: "/plaxis-animations"

plugins:
  - jekyll-remote-theme

# Hydeout es un fork que funciona muy bien con GitHub Pages
remote_theme: fongandrew/hydeout
